package com.example.movie_app.moviesSearch;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Update;
import org.springframework.stereotype.Service;

@Service
public class ReviewService {
    @Autowired
    private ReviewRepository reviewRepository;
    @Autowired
    private MongoTemplate mongoTemplate; // some operations are too complex to implement within a repo
    // so we use this template to create a dynamic query to modify database 

    public Review addReview(String reviewBody, String imdbID){

        Review review = reviewRepository.insert(new Review(reviewBody)); // ids are autogenerated we cannot pass that as an arg to the constructor
        // so we make a custom constructor to only take the body

        // now the review has to be connected to the movie obviously

         //this adds to the review collection

        // the template performs an update on the movie class where it finds the specific movie via its 
        //  imdbID and then inserts a review into the reviewID array
        mongoTemplate.update(Movie.class)
            .matching(Criteria.where("imdbID").is(imdbID))
            .apply(new Update().push("reviewID").value(review)) // the .apply makes the update to modify the db finally
            .first(); // updates the first document in the collection, assuming its the first document it comes across?

        return review;
    }
}
